# Input directory containing binning outputs (from MetaBin pipeline)
bins_dir: input_bins.dir

# Whether the input data was pooled or not
is_pooled: true  # set to false if running per-sample

# Parameters for bin refinement step
binrefinement:
  threads: 4
  job_memory: 10G
  completeness: 50
  contamination: 10

# List of binning tools to include in MetaWRAP bin_refinement.
# You must specify at least 2 and at most 3 tools.
# Supported values: metabat2, maxbin2, concoct, vamb
# The tools will be automatically assigned to flags -A, -B, and -C in the order listed.
# Example:
binning_tools:
  - metabat2
  - concoct
  
  
  
# Parameters for bin reassembly step
binreassembly:
  fastqs: prepped_fastqs.dir # symbolic links to prepped FASTQs generated during binning
  threads: 4
  job_memory: 10G
