# Input directory containing binning outputs (from MetaBin pipeline)
bins_dir: input_bins.dir

# Whether the input data was pooled or not
is_pooled: true  # set to false if running per-sample

#Parameters for bin refinement step
binrefinement:
  threads: 4
  job_memory: 10G
  completeness: 50
  contamination: 10

# Parameters for bin reassembly step
binreassembly:
  fastqs: prepped_fastqs.dir # For the unpooled scenario, create symbolic links to each sample's decompressed FASTQ files (i.e, sample1_1.fastq and sample1_2.fastq) from the prepped FASTQs generated during binning.If pooled, create symbolic links from the metaassembly pipeline 01_input_pooled.dir directory, where the FASTQ files were pooled and should follow the naming pattern xx.fastq.1.gz and xx.fastq.2.gz
  threads: 4
  job_memory: 10G
