hisat2:
    # index for reference genome
    ref_genome: /well/kir/mirror/genomes/hisat2/hg38.ensembl91.genome.dir/hg38

    # additional hisat2 options
    options: ''

    # cluster options
    job_threads: 10
    job_memory: 2G