################################################################
#
# Pipeline pipeline_mwgs_preprocess.py configuration file
# Add pipeline specific options into separate sections
#
################################################################
## general options

# Project name
projectname: Preprocess mWGS Samples

# Copyright statement
copyright: Jethro Johnson

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

#location_fastq: 0

# Sequence data type (metatranscriptome or metagenome)
data_type: metagenome


################################################################
# Removal of duplicate reads
################################################################
cdhit:

    # If yes, will remove exact duplicates
    dedup: 1

    # Additional options to be passed to cd-hit-dup
    options: ''

    # Cluster options
    job_threads: 4    

    job_memory: 48G


################################################################
# Trimming of adapters
################################################################
trimmomatic:

    jar_path: $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar

    n_threads: 4

    # Location of contaminants file
    # NexteraPE-PE.fa, TruSeq2-PE.fa, TruSeq3-PE-2.fa, TruSeq3-PE.fa
    # TruSeq2-SE.fa, TruSeq3-SE.fa
    adapters: /gpfs3/well/todd/projects/Microbiome/Ref_Databases/adapters/NEBNextUltraII-PE.fa

    phred_format: 33

    # Number of mismatches tolerated in seed alignment of adapter sequence (16 bases)
    seed_mismatches: 3

    # Identity threshold for palendromic match
    score_palendromic: 30

    # Identity threshold for simple clipping
    score_simple: 10

    min_adapter_len: 8

    # Whether to keep both reads if readthrough is detected
    keep_both_reads: true

    # Minimum quality before trimming 5'
    quality_leading: 25

    # Minumum quality before trimming 3'
    quality_trailing: 25

    # Minimum length for surviving read
    minlen: 36

    # Cluster options
    job_threads: 4

    job_memory: 20G


################################################################
# Removal of host contamination
################################################################
sortmerna:

    # Options for removing contaminant rRNA
    index: /gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_indexes/

    reference: /gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/rfam-5.8s-database-id98.fasta,/gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/rfam-5s-database-id98.fasta,/gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/silva-arc-16s-id95.fasta,/gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/silva-arc-23s-id98.fasta,/gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/silva-bac-16s-id90.fasta,/gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/ilva-bac-23s-id98.fasta,/gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/silva-euk-18s-id95.fasta,/gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/rRNA_databases/silva-euk-28s-id98.fasta 

    options: ''

    # Options for classfiying rRNA
    otu_index: /gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/16S_indexes/

    otu_reference: gpfs3/well/todd/projects/Microbiome/Ref_Databases/sortmerna/16S_databases/GTDB_bac-arc_ssu_r86.fasta

    otu_options: --id 0.97 --coverage 0.97 --de_novo_otu True  --otu_map True

    # Generic options
    job_threads: 12

    job_memory: 60G

# tool to use for host alignment and filtering. bmtagger or hisat
host_tool: hisat

bmtagger:

    # Set to true if you want to keep reads who's pair is host (currently disabled)
    # keep_pairs: ''

    # which executable to use - bmtagger_mod.sh fixes some apparent
    # bugs. Choices are bmtagger.sh or bmtagger_mod.sh
    executable: /users/todd/liu839/Scripts/bmtagger_debugged.sh

    # Comma-separated list of genomes to screen against
    bitmask: /gpfs3/well/todd/projects/Microbiome/Ref_Databases/bmtagger/bitmask/hg38.bitmask

    srprism: /gpfs3/well/todd/projects/Microbiome/Ref_Databases/human_genome/hg38.srprism
   
    # Cluster options  
    job_threads: 1

    job_memory: 25G

hisat2:
    # index for reference genome
    ref_genome: /well/kir/mirror/genomes/hisat2/hg38.ensembl91.genome.dir/hg38

    # additional hisat2 options
    options: ''

    # cluster options
    job_threads: 10
    job_memory: 2G
  
################################################################
# Masking or removal of repetitive sequence
################################################################
dust:

    # If yes, discard low complexity regions rather than softmask them
    discard_low_complexity: 1

    # 0.0001 mask homopolymers, 0.75 recommended
    entropy: 0.75

    # A comma-separated list of additional options
    # If bbmask, set window=64 to emulate dustmasker
    options: Xmx40g

    # Cluster options
    job_threads: 4
   
    job_memory: 40G   



