"""
================================
Align and remove host sequences
================================


Overview
========

This pipeline is based on CGATMetaSequencing pipeline_filter

1) Checks input files 
2) Map host reads with HISAT2
3) Filter reads from bam files


Configuration
=============
The pipeline requires a configured :file:`pipeline.yml` file.

Default configuration files can be generated by executing:
    
    ocms_shotgun remove_host config

Dependencies
============

HISAT2
SAMtools
BEDtools

source /well/kir/config/modules.sh
module load HISAT2/2.2.1-gompi-2022b
module load BEDTools/2.30.0-GCC-12.2.0
module load SAMtools/1.17-GCC-12.2.0

Code
====

"""

from ruffus import *
from cgatcore import pipeline as P
from cgatcore import iotools as IOTools

import os,sys

import ocmstoolkit.modules.Utility as Utility
import ocmsshotgun.modules.PreProcess as PP

# set up params
PARAMS = P.get_parameters(["pipeline.yml"])

# check that input files correspond
indir = PARAMS.get('general_input.dir', 'input.dir')
FASTQ1S = Utility.get_fastns(indir)

# forcing input.dir as input source because of filterMapping add_input.
# looking for a more flexible way of interacting with add_input
assert indir == 'input.dir', (
    "Input files need to be in input.dir."
)
################################################################################
# remove host sequences with bmtagger or hisat
################################################################################
@follows(mkdir('reads_hostRemoved.dir'))
@follows(removeRibosomalRNA)
@transform(removeRibosomalRNA,
           regex(r'reads_rrnaRemoved.dir/(\S+)_rRNAremoved.fastq.1.gz$'),
           r'reads_hostRemoved.dir/\1_dehost.fastq.1.gz')
def alignAndRemoveHost(infile,outfile): 
    '''Align and remove host sequences with bmtagger or HISAT2
    '''
    # bmtagger - aligns with srprism
    if PARAMS['host_tool']  == 'bmtagger':
        tool = PP.Bmtagger(infile, outfile, **PARAMS)
        statements, tmpfiles = tool.build_statement(Utility.MetaFastn(infile))

        # one statement for each host genome specified
        for statement in statements:
            P.run(statement, 
                job_threads=PARAMS['bmtagger_job_threads'], 
                job_memory=PARAMS['bmtagger_job_memory'],
                job_options=PARAMS.get('bmtagger_job_options',''))
        
        statement, to_unlink  = tool.post_process(Utility.MetaFastn(infile), tmpfiles)
        P.run(statement)
        for f in to_unlink:
            os.unlink(f)
    #Align host sequences with HISAT2 and remove host reads with samtools
    #converts the output from sam to bam
    elif PARAMS['host_tool'] == 'hisat':
        tool = PP.Hisat2(infile, outfile, **PARAMS)

        statement = tool.hisat2bam(Utility.MetaFastn(infile))
        
        statement = " ; ".join(statement)
        P.run(statement,
            job_threads = PARAMS["hisat2_job_threads"],
            job_memory = PARAMS["hisat2_job_memory"])
        
        # clean up sam files and hisat outputs
        statement = tool.post_process_pp()
        P.run(statement, without_cluster=True)

@active_if(PARAMS['host_tool'] == 'hisat')
@merge(alignAndRemoveHost,
       "reads_hostRemoved.dir/merged_hisat2_summary.tsv")
def mergeHisatSummary(infiles, outfile):
   # hisat summary logs
    logs = []
    for fq in infiles:
        fq_class = Utility.MetaFastn(fq)
        log = fq.replace(f"_dehost{fq_class.fq1_suffix}", "_hisat2_summary.log")
        logs.append(log)
    tool = PP.Hisat2(infiles[0], outfile, **PARAMS)
    tool.merge_hisat_summary(logs, outfile)

@active_if(PARAMS['host_tool'] == 'hisat')
@merge(alignAndRemoveHost,
       "reads_hostRemoved.dir/clean_up.log")
def cleanHisat(infiles, outfile):
    tool = PP.Hisat2(infiles[0], outfile, **PARAMS)
    statement = tool.clean_pp(outfile)

    P.run(statement, without_cluster=True)

@follows(alignAndRemoveHost, mergeHisatSummary)
def removeHost():
    pass

@follows(removeHost, mergeHisatSummary)
def full():
    pass

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)


if __name__ == "__main__":
    sys.exit(P.main(sys.argv))    