import sys
import os
import re
import glob
from pathlib import Path
from ruffus import *
from cgatcore import pipeline as P
import ocmstoolkit.modules.Utility as Utility

PARAMS = P.get_parameters("pipeline.yml")
indir=PARAMS["general_input.dir"]

#check all files to be processed
FASTQs = Utility.get_fastns(indir)

@follows(mkdir("metaphlan.dir"))
@transform(FASTQs,
           regex(r".*/(.+)\.fastq\.1\.gz"),
           r"metaphlan.dir/\1.metaphlan.profile.txt")
def runMetaphlan(infile, outfile):
    read1 = infile
    read2 = infile.replace(".1.gz", ".2.gz")
    
    sample = os.path.basename(P.snip(infile, ".fastq.1.gz"))
    db_path = PARAMS["metaphlan_db"]  # Using the full path directly
    
    statement = (
        "metaphlan {read1},{read2}" 
        " --input_type fastq" 
        " --bowtie2db {db_path}"
        " --nproc {threads}"
        " --index {db_ver}"
        " --bowtie2out metaphlan.dir/{sample}.bowtie2.bz2"
        " --tax_lev {tax_lev}"
        " -t rel_ab_w_read_stats"
        " -o {outfile}"
    ).format(
        read1=read1,
        read2=read2,
        db_path=db_path,
        db_ver=PARAMS["metaphlan_database_version"],
        sample=sample,
        threads=PARAMS["metaphlan_threads"],
        tax_lev=PARAMS["metaphlan_tax_lev"],
        outfile=outfile
    )
    
    if PARAMS["metaphlan_options"]:
        statement += ' ' + PARAMS["metaphlan_options"]
               
    P.run(statement,
          job_threads=PARAMS["metaphlan_threads"],
          job_memory=PARAMS["metaphlan_memory"],
          job_options=PARAMS["metaphlan_cluster_options"])

@follows(runMetaphlan)
@merge(runMetaphlan, "metaphlan.dir/merged_abundance_table.txt")
def mergeMetaphlanTables(infiles, outfile):
    infiles_str = " ".join(infiles)
    
    statement = f"merge_metaphlan_tables.py {infiles_str} > {outfile}"
    
    P.run(statement)


@follows(mkdir("taxonomy_relab.dir"))
@transform(mergeMetaphlanTables,
          regex(r"metaphlan.dir/merged_abundance_table.txt"),
          [r"taxonomy_relab.dir/kingdom.txt",
           r"taxonomy_relab.dir/phylum.txt",
           r"taxonomy_relab.dir/class.txt",
           r"taxonomy_relab.dir/order.txt",
           r"taxonomy_relab.dir/family.txt",
           r"taxonomy_relab.dir/genus.txt",
           r"taxonomy_relab.dir/species.txt",
           r"taxonomy_relab.dir/strain.txt"])

def extractTaxonomyLevelsRelAb(infile, outfiles):
    levels = ['k__', 'p__', 'c__', 'o__', 'f__', 'g__', 's__', 't__']

    for level, outfile in zip(levels, outfiles):
        statement = (
            f'(echo -e "$(head -n 2 {infile} | tail -n 1 | sed \'s/^clade_name/taxon/\')" && '
            f'grep "{level}" {infile}) > {outfile}'
        )
        P.run(statement)


@follows(mkdir("merged_metaphlan_counts.dir"))
@merge(runMetaphlan, "merged_metaphlan_counts.dir/merged_metaphlan_counts.txt.gz")
def mergeMetaphlanCounts(infiles, outfile):
    '''
    Merge raw count files from MetaPhlAn profiles generated by HUMAnN3 (or standalone MetaPhlAn).
    '''
    headers = [P.snip(os.path.basename(x), ".metaphlan.profile.txt") for x in infiles]
    headers_str = ",".join(headers)
    infile_glob = " ".join(infiles)


    statement = (
        f"ocms_shotgun combine_tables "
        f"--files {infile_glob} "
        f"--skip-titles "
        f"--header-names=\"{headers_str}\" "
        f"-m 0 "
        f"-k 5 "
        f"-c 1 "
        f"--log=merged_metaphlan_counts.dir/merged_metaphlan_counts.log "
        f"| gzip > {outfile} "
    )

    P.run(statement)

@follows(mergeMetaphlanCounts, mkdir("taxonomy_counts.dir"))
@transform("merged_metaphlan_counts.dir/merged_metaphlan_counts.txt.gz",
           regex(r"merged_metaphlan_counts.dir/merged_metaphlan_counts.txt.gz"),
           [r"taxonomy_counts.dir/kingdom.txt",
            r"taxonomy_counts.dir/phylum.txt",
            r"taxonomy_counts.dir/class.txt",
            r"taxonomy_counts.dir/order.txt",
            r"taxonomy_counts.dir/family.txt",
            r"taxonomy_counts.dir/genus.txt",
            r"taxonomy_counts.dir/species.txt",
            r"taxonomy_counts.dir/strain.txt"])
def extractTaxonomyLevelsCounts(infile, outfiles):
    levels = ['k__', 'p__', 'c__', 'o__', 'f__', 'g__', 's__', 't__']

    for level, outfile in zip(levels, outfiles):
        statement = (
            f'(echo -e "$(zcat {infile} | head -n 1 | sed \'s/^clade_name/taxon/\')" && '
            f'zcat {infile} | grep "{level}") > {outfile}'
        )
        P.run(statement)


@follows(runMetaphlan, mergeMetaphlanTables, extractTaxonomyLevelsRelAb, mergeMetaphlanCounts, extractTaxonomyLevelsCounts)
def full():
    pass

def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
