################################################################
#
# Pipeline pipeline_remove_host.py configuration file
# Add pipeline specific options into separate sections
#
################################################################
## general options
general:
  # The short X.Y version.
  version: 0.1

  # The full version, including alpha/beta/rc tags.
  release: 0.1

# tool to use for host alignment and filtering. bmtagger or hisat
host_tool: hisat

bmtagger:

    # Set to true if you want to keep reads who's pair is host (currently disabled)
    # keep_pairs: ''

    # which executable to use - bmtagger_mod.sh fixes some apparent
    # bugs. Choices are bmtagger.sh or bmtagger_mod.sh
    executable: bmtagger.sh

    # Comma-separated list of genomes to screen against
    bitmask: /gpfs3/well/johnson/shared/mirror/genome/bmtagger/bitmask/hg38.bitmask

    srprism: /gpfs3/well/johnson/shared/mirror/genome/bmtagger/srprism/hg38.srprism

   
    # Cluster options  
    job_threads: 1

    job_memory: 25G

hisat2:
    # index for reference genome
    ref_genome: /well/kir/mirror/genomes/hisat2/hg38.ensembl91.genome.dir/hg38

    # additional hisat2 options
    options: ''

    # cluster options
    job_threads: 10
    job_memory: 2G