# pipeline.yml

general:
  fasta_dir: input_metagenome_fasta.dir # directory with *.fasta files (individual or pooled)
  fastq_dir: input_metagenome_fastq.dir # directory with *.fastq.1.gz and *.fastq.2.gz


mapfastq2fasta:
  #For 1-1 mapping
  fastq_regex: (.+).fastq.1.gz
  fasta_regex: \1_index/\1.1.bt2
  output_regex: \1_depth.txt
  
  #For many to one mapping
  # All FASTQ samples prefixed with 'chow_' (e.g., chow_sample1, chow_sample2)
  # will be mapped to the same pooled reference assembly: chow_pooled.fasta
  # The pipeline will generate separate output files for each sample,
  # such as chow_sample1_depth.txt and chow_sample2_depth.txt
  #fastq_regex: ([^_]+)_(.+).fastq.1.gz
  #fasta_regex: \1_pooled_index/\1_pooled.1.bt2
  #output_regex: \1_\2_depth.txt
  threads: 8
