# pipeline.yml

general:
  fasta_dir: input_metagenome_fasta.dir # directory with *.fasta files (individual or pooled)
  fastq_dir: input_metagenome_fastq.dir # directory with *.fastq.1.gz and *.fastq.2.gz


mapfastq2fasta:
  #For 1-1 mapping
  fastq_regex: (.+).fastq.1.gz
  fasta_regex: \1_index/\1.1.bt2
  output_regex: \1.bam
  
  #For many to one mapping
  #fastq_regex: (.+)_.+.fastq.1.gz
  #fasta_regex: \1_pooled_index/\1_pooled.1.bt2
  #output_regex: \1_\2_depth.txt

  threads: 8
