
import os
import glob

class DepthFileManager:
    """
    Handles locating depth files for binning tools.
    Supports both one2one and many2one mapping modes.

    - In one2one mode:
        Each sample has its own depth file (e.g., <sample>_depth.txt).
        These files are expected to exist before running MetaBAT2,
        so we assert their existence to fail early if they are missing.

    - In many2one mode:
        A single cumulative depth file (cumulative_depth.txt) is used
        for pooled binning. This file is typically generated by a separate
        pipeline step (e.g., generate_cumulative_depth). Since it may not
        exist yet during pipeline setup, we do NOT assert its existence.
        Instead, we return the expected path and allow Ruffus to create
        it as part of the workflow.
    """

    def __init__(self, depth_dir="01_mapping.dir"):
        self.depth_dir = depth_dir

    def get_depth_files(self, mapping_mode):
        if mapping_mode == "many2one":
            # Single cumulative depth file
            return [os.path.join(self.depth_dir, "cumulative_depth.txt")]
        else:
            # Multiple depth files, one per sample
            depth_files = glob.glob(os.path.join(self.depth_dir, "*_depth.txt"))
            assert depth_files, f"No depth files found in {self.depth_dir}"
            return sorted(depth_files)

class MetaBAT2Runner:
    def __init__(self, assembly, depth_file, prefix, output_dir, **PARAMS):
        """
        Initialize MetaBAT2Runner using parameters from YAML config.
        """
        self.assembly = assembly
        self.depth_file = depth_file
        self.output_dir = output_dir
        self.prefix = prefix
        self.PARAMS = PARAMS

    def build_command(self):
        """
        Construct the MetaBAT2 command.
        """
        threads = self.PARAMS.get("threads", 4)
        min_contig_len = self.PARAMS.get("min_contig_length", 2500)

        os.makedirs(self.output_dir, exist_ok=True)
        out_prefix = os.path.join(self.output_dir, f"{self.prefix}_bin")
        log_file = os.path.join(self.output_dir, f"{self.prefix}_metabat2.log")

        return (
            f"metabat2 -i {self.assembly} "
            f"-a {self.depth_file} "
            f"-o {out_prefix} "
            f"-m {min_contig_len} "
            f"-t {threads} "
            f"> {log_file} 2>&1 && gzip -f {out_prefix}.*.fa"
        )

    # -------------------------------------------------------------------------
    # Unified Static Methods
    # -------------------------------------------------------------------------
    @staticmethod
    def run_for_sample(depth_file, output_dir, PARAMS, pooled=False):
        """
        Build a MetaBAT2 command for either a single sample (one2one) or pooled mode.

        Parameters:
        - depth_file: Path to the depth file.
        - output_dir: Target directory for bins.
        - PARAMS: Pipeline configuration.
        - pooled: Boolean indicating if pooled mode is active.

        Returns:
        - Command string for running MetaBAT2.
        """
        fasta_dir = PARAMS["general"]["fasta_dir"]

        if pooled:
            # Find pooled FASTA
            fasta_files = glob.glob(os.path.join(fasta_dir, "*.fasta"))
            if len(fasta_files) != 1:
                raise FileNotFoundError(f"Expected 1 pooled FASTA in {fasta_dir}, found: {fasta_files}")
            fasta_path = fasta_files[0]
            prefix = os.path.splitext(os.path.basename(fasta_path))[0]
        else:
            # Standard one-to-one mapping
            prefix = os.path.basename(depth_file).replace("_depth.txt", "")
            fasta_path = os.path.join(fasta_dir, f"{prefix}.fasta")
            if not os.path.exists(fasta_path):
                raise FileNotFoundError(f"FASTA not found for {depth_file}: {fasta_path}")

        binner = MetaBAT2Runner(
            assembly=fasta_path,
            depth_file=depth_file,
            prefix=prefix,
            output_dir=output_dir,
            **PARAMS["metabat2"]
        )
        return binner.build_command()

    @staticmethod
    def run_all(output_dir, mapping_mode, PARAMS):
        """
        Build MetaBAT2 commands for all samples (one2one) or a single pooled run (many2one).
        """
        depth_manager = DepthFileManager()
        depth_files = depth_manager.get_depth_files(mapping_mode)

        commands = []
        pooled = mapping_mode == "many2one"

        for depth_file in depth_files:
            # Determine sample or pooled directory
            prefix = "pooled" if pooled else os.path.basename(depth_file).replace("_depth.txt", "")
            sample_dir = os.path.join(output_dir, prefix, "metabat2_bins")
            os.makedirs(sample_dir, exist_ok=True)

            cmd = MetaBAT2Runner.run_for_sample(depth_file, sample_dir, PARAMS, pooled=pooled)
            commands.append((prefix, cmd))

        return commands

class MaxBin2Runner:
    def __init__(self, assembly, prefix, output_dir, abundance_file=None, abundance_list=None, **PARAMS):
        """
        Initialize MaxBin2Runner using parameters from YAML config.

        :param assembly: Path to assembly FASTA file
        :param abundance_file: Path to abundance/depth file (for unpooled samples)
        :param abundance_list: Path to abundance list file (for pooled samples)
        :param output_dir: Output directory for MaxBin2 bins
        :param prefix: Prefix for output bin files
        :param PARAMS: Additional parameter like maxbin2_threads
        """
        self.assembly = assembly
        self.abundance_file = abundance_file
        self.abundance_list = abundance_list
        self.output_dir = output_dir
        self.prefix = prefix
        self.PARAMS = PARAMS

    def build_command(self):
        """
        Build statement for MaxBin2.
        """
        maxbin2_threads = self.PARAMS.get("maxbin2_threads", 4)

        output_prefix = os.path.join(self.output_dir, f"{self.prefix}_bin")

        statement = (
            f"MaxBin "
            f"-fasta {self.assembly} "
            f"-out {output_prefix} "
            f"-thread {maxbin2_threads}"
        )
        # Add abundance file or list
        if self.abundance_list:
            statement += f" -abund_list {self.abundance_list}"
        elif self.abundance_file:
            statement += f" -abund {self.abundance_file}"

        return statement.strip()

