################################################################
# Pipeline configuration file for MetaPHlAn4 pipeline
################################################################

# Pipeline metadata
projectname: metaphlan4_pipeline
copyright: CGAT
version: 0.1

metaphlan:
    # Path to existing MetaPHlAn database
    db: /users/powrie/cqh100/shared/metaphlan4/bowtie2index
    database_version: mpa_vJun23_CHOCOPhlAnSGB_202403

    # Analysis parameters
    threads: 16
    memory: 32G
    tax_lev: a
    options: ''
    
    # Job options
    cluster_options: ''